# Generated by Django 4.2 on 2024-03-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('auteur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_auteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieLivre',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('livre_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('nombre_livres', models.IntegerField(default=0)),
                ('prix_locations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couverture', models.ImageField(blank=True, upload_to='images_cover/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.auteur')),
                ('categorie', models.ManyToManyField(to='biblio.categorielivre')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_location', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.livre')),
            ],
        ),
        migrations.AddConstraint(
            model_name='auteur',
            constraint=models.UniqueConstraint(fields=('nom_auteur',), name='unique_auteur_name'),
        ),
    ]
