# Generated by Django 4.2 on 2024-03-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClient',
            fields=[
                ('question_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.client')),
            ],
        ),
    ]
