# Generated by Django 4.2 on 2024-03-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_questionclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionclient',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
