# Generated by Django 4.2 on 2024-03-11 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_questionclient_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.livre')),
            ],
        ),
    ]
