# Generated by Django 4.2 on 2024-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
