# Generated by Django 4.2 on 2024-03-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_client_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo_profil',
        ),
    ]
