# Generated by Django 4.2 on 2024-03-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_remove_client_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('photo_profil_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio.client')),
            ],
        ),
    ]
