# Generated by Django 4.2 on 2024-03-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_photoprofil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoProfil',
        ),
    ]
